package Assignment2;

public class compate_trans {

    public static void main(String[] args) {
        String givenSeq = "GGCGGAGGTTGCAGTTGCAGTTGCAGTGAGCTGAGATCACGCCACTGCACTCCACTTGGGCGACAGAGCGAGACTCTGTCTCCAAAAAATAAATTAGTAAATAAAAGATATGAGTAAAGATTGCCAAGAAGTTCATTGGCGGCCTCTGTTTTGTTTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTTGAACAGTTGCCAGTAGTCATCAGAGTACCAAAACTGATCTATTTCTCAGTAATGAGTGTGTGCCTCATGCCTGTTTCAATATTGGGTTTTGGAGACATTATTGTACCAGGCCTGTTGATTGCATACTGTAGAAGATTT";
        String resulSeq = "GGCGGAGGTTGCAGTTGCAGTTGCAGTGAGCTGAGATCACGCCACTGCACTCCACTTGGGCGACAGAGCGAGACTCTGTCTCCAAAAAATAAATTAGTAAATAAAAGATATGAGTAAAGATTGCCAAGAAGTTCATTGGCGGCCTCTGTTTTGTTTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTTGAACAGTTGCCAGTAGTCATCAGAGTACCAAAACTGATCTATTTCTCAGTAATGAGTGTGTGCCTCATGCCTGTTTCAATATTGGGTTTTGGAGACATTATTGTACCAGGCCTGTTGATTGCATACTGTAGAAGATTT";

        if(givenSeq.equals(resulSeq)){
            System.out.println("true");
        }
    }
}
